require('lazy').setup({
  require 'plugins.guess-indent',
  require 'plugins.gitsigns',
  require 'plugins.which-key',
  require 'plugins.lspconfig',
  require 'plugins.fzf-lua',
  require 'plugins.conform',
  require 'plugins.blink-cmp',
  require 'plugins.tokyonight',
  require 'plugins.todo-comments',
  require 'plugins.mini',
  require 'plugins.treesitter',
  require 'plugins.debug',
  require 'plugins.indent-blankline',
  require 'plugins.lint',
  require 'plugins.autopairs',
  require 'plugins.markview',
  require 'plugins.oil',
  require 'plugins.smart-splits',
  require 'plugins.undotree',
  require 'plugins.vim-matchup',
  require 'plugins.vim-suda',
}, {
  ui = {
    border = 'rounded',
    icons = vim.g.has_nerd_font and {} or {
      cmd = '⌘',
      config = '🛠',
      event = '📅',
      ft = '📂',
      init = '⚙',
      keys = '🗝',
      plugin = '🔌',
      runtime = '💻',
      require = '🌙',
      source = '📄',
      start = '🚀',
      task = '📌',
      lazy = '💤',
    },
  },
})

-- vim: ts=2 sts=2 sw=2 et
